function xdot = SymDynamics3DoF_mass_constant_noumag(t,in2,in3,L,I,m)
%SymDynamics3DoF_mass_constant_noumag
%    XDOT = SymDynamics3DoF_mass_constant_noumag(T,IN2,IN3,L,I,M)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Oct-2025 15:57:27

theta1 = in2(5,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
w1 = in2(6,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = 1.0./m;
xdot = [v1;v2;t4.*(t2.*thrust1-t3.*thrust2);t4.*(t2.*thrust2+t3.*thrust1)-9.81e-3;w1;-(L.*thrust2)./I];
end
