src_folders = { ...
    "Earth2Ast_fixed_FOH_PTR_ECOS/c/src", ...
    "Earth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/src", ...
    "Earth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/ecos_bb", ...
	"Earth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/external/amd/src/", ...
	"Earth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/external/ldl/src/", ...
};

% Collect all .c files from each folder
all_src_files = {};
for k = 1:numel(src_folders)
    src_info = dir(fullfile(src_folders{k}, "*.c"));
    % full paths as cell array
    all_src_files = [all_src_files, fullfile({src_info.folder}, {src_info.name})];
end

mex( ...
    "cpg_solve_wrap_Earth2Ast.c", ...
    all_src_files{:}, ...
    "-I./Earth2Ast_fixed_FOH_PTR_ECOS/c/include", ...
    "-IEarth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/include", ...
    "-IEarth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/external/amd/include", ...
    "-IEarth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/external/ldl/include", ...
    "-IEarth2Ast_fixed_FOH_PTR_ECOS/c/solver_code/external/SuiteSparse_config" ...
);