
/*
Auto-generated by CVXPYgen on September 15, 2025 at 01:13:44.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_Ak_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+49] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+70] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_ck(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+91] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+189] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+238] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+259] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+280] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+329] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+350] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+371] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+420] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+441] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+462] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+511] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+532] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+553] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+602] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+623] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+644] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+693] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+714] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+735] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+784] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+805] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+826] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+875] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+896] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+917] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+966] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+987] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1008] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1057] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1078] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1099] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1148] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1169] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1190] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1239] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1260] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1281] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1330] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1351] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_x_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1372] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_f(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1379] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1385] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_u_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1490] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<1589; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<153; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<600; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.U[0] = ecos_workspace->x[143];
  CPG_Prim.U[1] = ecos_workspace->x[144];
  CPG_Prim.U[2] = ecos_workspace->x[145];
  CPG_Prim.U[3] = ecos_workspace->x[146];
  CPG_Prim.U[4] = ecos_workspace->x[147];
  CPG_Prim.U[5] = ecos_workspace->x[148];
  CPG_Prim.U[6] = ecos_workspace->x[149];
  CPG_Prim.U[7] = ecos_workspace->x[150];
  CPG_Prim.U[8] = ecos_workspace->x[151];
  CPG_Prim.U[9] = ecos_workspace->x[152];
  CPG_Prim.U[10] = ecos_workspace->x[153];
  CPG_Prim.U[11] = ecos_workspace->x[154];
  CPG_Prim.U[12] = ecos_workspace->x[155];
  CPG_Prim.U[13] = ecos_workspace->x[156];
  CPG_Prim.U[14] = ecos_workspace->x[157];
  CPG_Prim.U[15] = ecos_workspace->x[158];
  CPG_Prim.U[16] = ecos_workspace->x[159];
  CPG_Prim.U[17] = ecos_workspace->x[160];
  CPG_Prim.U[18] = ecos_workspace->x[161];
  CPG_Prim.U[19] = ecos_workspace->x[162];
  CPG_Prim.U[20] = ecos_workspace->x[163];
  CPG_Prim.U[21] = ecos_workspace->x[164];
  CPG_Prim.U[22] = ecos_workspace->x[165];
  CPG_Prim.U[23] = ecos_workspace->x[166];
  CPG_Prim.U[24] = ecos_workspace->x[167];
  CPG_Prim.U[25] = ecos_workspace->x[168];
  CPG_Prim.U[26] = ecos_workspace->x[169];
  CPG_Prim.U[27] = ecos_workspace->x[170];
  CPG_Prim.U[28] = ecos_workspace->x[171];
  CPG_Prim.U[29] = ecos_workspace->x[172];
  CPG_Prim.U[30] = ecos_workspace->x[173];
  CPG_Prim.U[31] = ecos_workspace->x[174];
  CPG_Prim.U[32] = ecos_workspace->x[175];
  CPG_Prim.U[33] = ecos_workspace->x[176];
  CPG_Prim.U[34] = ecos_workspace->x[177];
  CPG_Prim.U[35] = ecos_workspace->x[178];
  CPG_Prim.U[36] = ecos_workspace->x[179];
  CPG_Prim.U[37] = ecos_workspace->x[180];
  CPG_Prim.U[38] = ecos_workspace->x[181];
  CPG_Prim.U[39] = ecos_workspace->x[182];
  CPG_Prim.U[40] = ecos_workspace->x[183];
  CPG_Prim.U[41] = ecos_workspace->x[184];
  CPG_Prim.U[42] = ecos_workspace->x[185];
  CPG_Prim.U[43] = ecos_workspace->x[186];
  CPG_Prim.U[44] = ecos_workspace->x[187];
  CPG_Prim.V[0] = ecos_workspace->x[188];
  CPG_Prim.V[1] = ecos_workspace->x[189];
  CPG_Prim.V[2] = ecos_workspace->x[190];
  CPG_Prim.V[3] = ecos_workspace->x[191];
  CPG_Prim.V[4] = ecos_workspace->x[192];
  CPG_Prim.V[5] = ecos_workspace->x[193];
  CPG_Prim.V[6] = ecos_workspace->x[194];
  CPG_Prim.V[7] = ecos_workspace->x[195];
  CPG_Prim.V[8] = ecos_workspace->x[196];
  CPG_Prim.V[9] = ecos_workspace->x[197];
  CPG_Prim.V[10] = ecos_workspace->x[198];
  CPG_Prim.V[11] = ecos_workspace->x[199];
  CPG_Prim.V[12] = ecos_workspace->x[200];
  CPG_Prim.V[13] = ecos_workspace->x[201];
  CPG_Prim.V[14] = ecos_workspace->x[202];
  CPG_Prim.V[15] = ecos_workspace->x[203];
  CPG_Prim.V[16] = ecos_workspace->x[204];
  CPG_Prim.V[17] = ecos_workspace->x[205];
  CPG_Prim.V[18] = ecos_workspace->x[206];
  CPG_Prim.V[19] = ecos_workspace->x[207];
  CPG_Prim.V[20] = ecos_workspace->x[208];
  CPG_Prim.V[21] = ecos_workspace->x[209];
  CPG_Prim.V[22] = ecos_workspace->x[210];
  CPG_Prim.V[23] = ecos_workspace->x[211];
  CPG_Prim.V[24] = ecos_workspace->x[212];
  CPG_Prim.V[25] = ecos_workspace->x[213];
  CPG_Prim.V[26] = ecos_workspace->x[214];
  CPG_Prim.V[27] = ecos_workspace->x[215];
  CPG_Prim.V[28] = ecos_workspace->x[216];
  CPG_Prim.V[29] = ecos_workspace->x[217];
  CPG_Prim.V[30] = ecos_workspace->x[218];
  CPG_Prim.V[31] = ecos_workspace->x[219];
  CPG_Prim.V[32] = ecos_workspace->x[220];
  CPG_Prim.V[33] = ecos_workspace->x[221];
  CPG_Prim.V[34] = ecos_workspace->x[222];
  CPG_Prim.V[35] = ecos_workspace->x[223];
  CPG_Prim.V[36] = ecos_workspace->x[224];
  CPG_Prim.V[37] = ecos_workspace->x[225];
  CPG_Prim.V[38] = ecos_workspace->x[226];
  CPG_Prim.V[39] = ecos_workspace->x[227];
  CPG_Prim.V[40] = ecos_workspace->x[228];
  CPG_Prim.V[41] = ecos_workspace->x[229];
  CPG_Prim.V[42] = ecos_workspace->x[230];
  CPG_Prim.V[43] = ecos_workspace->x[231];
  CPG_Prim.V[44] = ecos_workspace->x[232];
  CPG_Prim.V[45] = ecos_workspace->x[233];
  CPG_Prim.V[46] = ecos_workspace->x[234];
  CPG_Prim.V[47] = ecos_workspace->x[235];
  CPG_Prim.V[48] = ecos_workspace->x[236];
  CPG_Prim.V[49] = ecos_workspace->x[237];
  CPG_Prim.V[50] = ecos_workspace->x[238];
  CPG_Prim.V[51] = ecos_workspace->x[239];
  CPG_Prim.V[52] = ecos_workspace->x[240];
  CPG_Prim.V[53] = ecos_workspace->x[241];
  CPG_Prim.V[54] = ecos_workspace->x[242];
  CPG_Prim.V[55] = ecos_workspace->x[243];
  CPG_Prim.V[56] = ecos_workspace->x[244];
  CPG_Prim.V[57] = ecos_workspace->x[245];
  CPG_Prim.V[58] = ecos_workspace->x[246];
  CPG_Prim.V[59] = ecos_workspace->x[247];
  CPG_Prim.V[60] = ecos_workspace->x[248];
  CPG_Prim.V[61] = ecos_workspace->x[249];
  CPG_Prim.V[62] = ecos_workspace->x[250];
  CPG_Prim.V[63] = ecos_workspace->x[251];
  CPG_Prim.V[64] = ecos_workspace->x[252];
  CPG_Prim.V[65] = ecos_workspace->x[253];
  CPG_Prim.V[66] = ecos_workspace->x[254];
  CPG_Prim.V[67] = ecos_workspace->x[255];
  CPG_Prim.V[68] = ecos_workspace->x[256];
  CPG_Prim.V[69] = ecos_workspace->x[257];
  CPG_Prim.V[70] = ecos_workspace->x[258];
  CPG_Prim.V[71] = ecos_workspace->x[259];
  CPG_Prim.V[72] = ecos_workspace->x[260];
  CPG_Prim.V[73] = ecos_workspace->x[261];
  CPG_Prim.V[74] = ecos_workspace->x[262];
  CPG_Prim.V[75] = ecos_workspace->x[263];
  CPG_Prim.V[76] = ecos_workspace->x[264];
  CPG_Prim.V[77] = ecos_workspace->x[265];
  CPG_Prim.V[78] = ecos_workspace->x[266];
  CPG_Prim.V[79] = ecos_workspace->x[267];
  CPG_Prim.V[80] = ecos_workspace->x[268];
  CPG_Prim.V[81] = ecos_workspace->x[269];
  CPG_Prim.V[82] = ecos_workspace->x[270];
  CPG_Prim.V[83] = ecos_workspace->x[271];
  CPG_Prim.V[84] = ecos_workspace->x[272];
  CPG_Prim.V[85] = ecos_workspace->x[273];
  CPG_Prim.V[86] = ecos_workspace->x[274];
  CPG_Prim.V[87] = ecos_workspace->x[275];
  CPG_Prim.V[88] = ecos_workspace->x[276];
  CPG_Prim.V[89] = ecos_workspace->x[277];
  CPG_Prim.V[90] = ecos_workspace->x[278];
  CPG_Prim.V[91] = ecos_workspace->x[279];
  CPG_Prim.V[92] = ecos_workspace->x[280];
  CPG_Prim.V[93] = ecos_workspace->x[281];
  CPG_Prim.V[94] = ecos_workspace->x[282];
  CPG_Prim.V[95] = ecos_workspace->x[283];
  CPG_Prim.V[96] = ecos_workspace->x[284];
  CPG_Prim.V[97] = ecos_workspace->x[285];
  CPG_Prim.v_0[0] = ecos_workspace->x[286];
  CPG_Prim.v_0[1] = ecos_workspace->x[287];
  CPG_Prim.v_0[2] = ecos_workspace->x[288];
  CPG_Prim.v_0[3] = ecos_workspace->x[289];
  CPG_Prim.v_0[4] = ecos_workspace->x[290];
  CPG_Prim.v_0[5] = ecos_workspace->x[291];
  CPG_Prim.v_0[6] = ecos_workspace->x[292];
  CPG_Prim.v_N[0] = ecos_workspace->x[300];
  CPG_Prim.v_N[1] = ecos_workspace->x[301];
  CPG_Prim.v_N[2] = ecos_workspace->x[302];
  CPG_Prim.v_N[3] = ecos_workspace->x[303];
  CPG_Prim.v_N[4] = ecos_workspace->x[304];
  CPG_Prim.v_N[5] = ecos_workspace->x[305];
  CPG_Prim.eta[0] = ecos_workspace->x[128];
  CPG_Prim.eta[1] = ecos_workspace->x[129];
  CPG_Prim.eta[2] = ecos_workspace->x[130];
  CPG_Prim.eta[3] = ecos_workspace->x[131];
  CPG_Prim.eta[4] = ecos_workspace->x[132];
  CPG_Prim.eta[5] = ecos_workspace->x[133];
  CPG_Prim.eta[6] = ecos_workspace->x[134];
  CPG_Prim.eta[7] = ecos_workspace->x[135];
  CPG_Prim.eta[8] = ecos_workspace->x[136];
  CPG_Prim.eta[9] = ecos_workspace->x[137];
  CPG_Prim.eta[10] = ecos_workspace->x[138];
  CPG_Prim.eta[11] = ecos_workspace->x[139];
  CPG_Prim.eta[12] = ecos_workspace->x[140];
  CPG_Prim.eta[13] = ecos_workspace->x[141];
  CPG_Prim.eta[14] = ecos_workspace->x[142];
  CPG_Prim.X[0] = ecos_workspace->x[312];
  CPG_Prim.X[1] = ecos_workspace->x[313];
  CPG_Prim.X[2] = ecos_workspace->x[314];
  CPG_Prim.X[3] = ecos_workspace->x[315];
  CPG_Prim.X[4] = ecos_workspace->x[316];
  CPG_Prim.X[5] = ecos_workspace->x[317];
  CPG_Prim.X[6] = ecos_workspace->x[318];
  CPG_Prim.X[7] = ecos_workspace->x[319];
  CPG_Prim.X[8] = ecos_workspace->x[320];
  CPG_Prim.X[9] = ecos_workspace->x[321];
  CPG_Prim.X[10] = ecos_workspace->x[322];
  CPG_Prim.X[11] = ecos_workspace->x[323];
  CPG_Prim.X[12] = ecos_workspace->x[324];
  CPG_Prim.X[13] = ecos_workspace->x[325];
  CPG_Prim.X[14] = ecos_workspace->x[326];
  CPG_Prim.X[15] = ecos_workspace->x[327];
  CPG_Prim.X[16] = ecos_workspace->x[328];
  CPG_Prim.X[17] = ecos_workspace->x[329];
  CPG_Prim.X[18] = ecos_workspace->x[330];
  CPG_Prim.X[19] = ecos_workspace->x[331];
  CPG_Prim.X[20] = ecos_workspace->x[332];
  CPG_Prim.X[21] = ecos_workspace->x[333];
  CPG_Prim.X[22] = ecos_workspace->x[334];
  CPG_Prim.X[23] = ecos_workspace->x[335];
  CPG_Prim.X[24] = ecos_workspace->x[336];
  CPG_Prim.X[25] = ecos_workspace->x[337];
  CPG_Prim.X[26] = ecos_workspace->x[338];
  CPG_Prim.X[27] = ecos_workspace->x[339];
  CPG_Prim.X[28] = ecos_workspace->x[340];
  CPG_Prim.X[29] = ecos_workspace->x[341];
  CPG_Prim.X[30] = ecos_workspace->x[342];
  CPG_Prim.X[31] = ecos_workspace->x[343];
  CPG_Prim.X[32] = ecos_workspace->x[344];
  CPG_Prim.X[33] = ecos_workspace->x[345];
  CPG_Prim.X[34] = ecos_workspace->x[346];
  CPG_Prim.X[35] = ecos_workspace->x[347];
  CPG_Prim.X[36] = ecos_workspace->x[348];
  CPG_Prim.X[37] = ecos_workspace->x[349];
  CPG_Prim.X[38] = ecos_workspace->x[350];
  CPG_Prim.X[39] = ecos_workspace->x[351];
  CPG_Prim.X[40] = ecos_workspace->x[352];
  CPG_Prim.X[41] = ecos_workspace->x[353];
  CPG_Prim.X[42] = ecos_workspace->x[354];
  CPG_Prim.X[43] = ecos_workspace->x[355];
  CPG_Prim.X[44] = ecos_workspace->x[356];
  CPG_Prim.X[45] = ecos_workspace->x[357];
  CPG_Prim.X[46] = ecos_workspace->x[358];
  CPG_Prim.X[47] = ecos_workspace->x[359];
  CPG_Prim.X[48] = ecos_workspace->x[360];
  CPG_Prim.X[49] = ecos_workspace->x[361];
  CPG_Prim.X[50] = ecos_workspace->x[362];
  CPG_Prim.X[51] = ecos_workspace->x[363];
  CPG_Prim.X[52] = ecos_workspace->x[364];
  CPG_Prim.X[53] = ecos_workspace->x[365];
  CPG_Prim.X[54] = ecos_workspace->x[366];
  CPG_Prim.X[55] = ecos_workspace->x[367];
  CPG_Prim.X[56] = ecos_workspace->x[368];
  CPG_Prim.X[57] = ecos_workspace->x[369];
  CPG_Prim.X[58] = ecos_workspace->x[370];
  CPG_Prim.X[59] = ecos_workspace->x[371];
  CPG_Prim.X[60] = ecos_workspace->x[372];
  CPG_Prim.X[61] = ecos_workspace->x[373];
  CPG_Prim.X[62] = ecos_workspace->x[374];
  CPG_Prim.X[63] = ecos_workspace->x[375];
  CPG_Prim.X[64] = ecos_workspace->x[376];
  CPG_Prim.X[65] = ecos_workspace->x[377];
  CPG_Prim.X[66] = ecos_workspace->x[378];
  CPG_Prim.X[67] = ecos_workspace->x[379];
  CPG_Prim.X[68] = ecos_workspace->x[380];
  CPG_Prim.X[69] = ecos_workspace->x[381];
  CPG_Prim.X[70] = ecos_workspace->x[382];
  CPG_Prim.X[71] = ecos_workspace->x[383];
  CPG_Prim.X[72] = ecos_workspace->x[384];
  CPG_Prim.X[73] = ecos_workspace->x[385];
  CPG_Prim.X[74] = ecos_workspace->x[386];
  CPG_Prim.X[75] = ecos_workspace->x[387];
  CPG_Prim.X[76] = ecos_workspace->x[388];
  CPG_Prim.X[77] = ecos_workspace->x[389];
  CPG_Prim.X[78] = ecos_workspace->x[390];
  CPG_Prim.X[79] = ecos_workspace->x[391];
  CPG_Prim.X[80] = ecos_workspace->x[392];
  CPG_Prim.X[81] = ecos_workspace->x[393];
  CPG_Prim.X[82] = ecos_workspace->x[394];
  CPG_Prim.X[83] = ecos_workspace->x[395];
  CPG_Prim.X[84] = ecos_workspace->x[396];
  CPG_Prim.X[85] = ecos_workspace->x[397];
  CPG_Prim.X[86] = ecos_workspace->x[398];
  CPG_Prim.X[87] = ecos_workspace->x[399];
  CPG_Prim.X[88] = ecos_workspace->x[400];
  CPG_Prim.X[89] = ecos_workspace->x[401];
  CPG_Prim.X[90] = ecos_workspace->x[402];
  CPG_Prim.X[91] = ecos_workspace->x[403];
  CPG_Prim.X[92] = ecos_workspace->x[404];
  CPG_Prim.X[93] = ecos_workspace->x[405];
  CPG_Prim.X[94] = ecos_workspace->x[406];
  CPG_Prim.X[95] = ecos_workspace->x[407];
  CPG_Prim.X[96] = ecos_workspace->x[408];
  CPG_Prim.X[97] = ecos_workspace->x[409];
  CPG_Prim.X[98] = ecos_workspace->x[410];
  CPG_Prim.X[99] = ecos_workspace->x[411];
  CPG_Prim.X[100] = ecos_workspace->x[412];
  CPG_Prim.X[101] = ecos_workspace->x[413];
  CPG_Prim.X[102] = ecos_workspace->x[414];
  CPG_Prim.X[103] = ecos_workspace->x[415];
  CPG_Prim.X[104] = ecos_workspace->x[416];
  CPG_Prim.p[0] = ecos_workspace->x[433];
  CPG_Prim.p[1] = ecos_workspace->x[434];
  CPG_Prim.p[2] = ecos_workspace->x[435];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = ecos_workspace->y[0];
  CPG_Dual.d0[1] = ecos_workspace->y[1];
  CPG_Dual.d0[2] = ecos_workspace->y[2];
  CPG_Dual.d0[3] = ecos_workspace->y[3];
  CPG_Dual.d0[4] = ecos_workspace->y[4];
  CPG_Dual.d0[5] = ecos_workspace->y[5];
  CPG_Dual.d0[6] = ecos_workspace->y[6];
  CPG_Dual.d1[0] = ecos_workspace->y[7];
  CPG_Dual.d1[1] = ecos_workspace->y[8];
  CPG_Dual.d1[2] = ecos_workspace->y[9];
  CPG_Dual.d1[3] = ecos_workspace->y[10];
  CPG_Dual.d1[4] = ecos_workspace->y[11];
  CPG_Dual.d1[5] = ecos_workspace->y[12];
  CPG_Dual.d1[6] = ecos_workspace->y[13];
  CPG_Dual.d2[0] = ecos_workspace->y[14];
  CPG_Dual.d2[1] = ecos_workspace->y[15];
  CPG_Dual.d2[2] = ecos_workspace->y[16];
  CPG_Dual.d2[3] = ecos_workspace->y[17];
  CPG_Dual.d2[4] = ecos_workspace->y[18];
  CPG_Dual.d2[5] = ecos_workspace->y[19];
  CPG_Dual.d2[6] = ecos_workspace->y[20];
  CPG_Dual.d3[0] = ecos_workspace->y[21];
  CPG_Dual.d3[1] = ecos_workspace->y[22];
  CPG_Dual.d3[2] = ecos_workspace->y[23];
  CPG_Dual.d3[3] = ecos_workspace->y[24];
  CPG_Dual.d3[4] = ecos_workspace->y[25];
  CPG_Dual.d3[5] = ecos_workspace->y[26];
  CPG_Dual.d3[6] = ecos_workspace->y[27];
  CPG_Dual.d4[0] = ecos_workspace->y[28];
  CPG_Dual.d4[1] = ecos_workspace->y[29];
  CPG_Dual.d4[2] = ecos_workspace->y[30];
  CPG_Dual.d4[3] = ecos_workspace->y[31];
  CPG_Dual.d4[4] = ecos_workspace->y[32];
  CPG_Dual.d4[5] = ecos_workspace->y[33];
  CPG_Dual.d4[6] = ecos_workspace->y[34];
  CPG_Dual.d5[0] = ecos_workspace->y[35];
  CPG_Dual.d5[1] = ecos_workspace->y[36];
  CPG_Dual.d5[2] = ecos_workspace->y[37];
  CPG_Dual.d5[3] = ecos_workspace->y[38];
  CPG_Dual.d5[4] = ecos_workspace->y[39];
  CPG_Dual.d5[5] = ecos_workspace->y[40];
  CPG_Dual.d5[6] = ecos_workspace->y[41];
  CPG_Dual.d6[0] = ecos_workspace->y[42];
  CPG_Dual.d6[1] = ecos_workspace->y[43];
  CPG_Dual.d6[2] = ecos_workspace->y[44];
  CPG_Dual.d6[3] = ecos_workspace->y[45];
  CPG_Dual.d6[4] = ecos_workspace->y[46];
  CPG_Dual.d6[5] = ecos_workspace->y[47];
  CPG_Dual.d6[6] = ecos_workspace->y[48];
  CPG_Dual.d7[0] = ecos_workspace->y[49];
  CPG_Dual.d7[1] = ecos_workspace->y[50];
  CPG_Dual.d7[2] = ecos_workspace->y[51];
  CPG_Dual.d7[3] = ecos_workspace->y[52];
  CPG_Dual.d7[4] = ecos_workspace->y[53];
  CPG_Dual.d7[5] = ecos_workspace->y[54];
  CPG_Dual.d7[6] = ecos_workspace->y[55];
  CPG_Dual.d8[0] = ecos_workspace->y[56];
  CPG_Dual.d8[1] = ecos_workspace->y[57];
  CPG_Dual.d8[2] = ecos_workspace->y[58];
  CPG_Dual.d8[3] = ecos_workspace->y[59];
  CPG_Dual.d8[4] = ecos_workspace->y[60];
  CPG_Dual.d8[5] = ecos_workspace->y[61];
  CPG_Dual.d8[6] = ecos_workspace->y[62];
  CPG_Dual.d9[0] = ecos_workspace->y[63];
  CPG_Dual.d9[1] = ecos_workspace->y[64];
  CPG_Dual.d9[2] = ecos_workspace->y[65];
  CPG_Dual.d9[3] = ecos_workspace->y[66];
  CPG_Dual.d9[4] = ecos_workspace->y[67];
  CPG_Dual.d9[5] = ecos_workspace->y[68];
  CPG_Dual.d9[6] = ecos_workspace->y[69];
  CPG_Dual.d10[0] = ecos_workspace->y[70];
  CPG_Dual.d10[1] = ecos_workspace->y[71];
  CPG_Dual.d10[2] = ecos_workspace->y[72];
  CPG_Dual.d10[3] = ecos_workspace->y[73];
  CPG_Dual.d10[4] = ecos_workspace->y[74];
  CPG_Dual.d10[5] = ecos_workspace->y[75];
  CPG_Dual.d10[6] = ecos_workspace->y[76];
  CPG_Dual.d11[0] = ecos_workspace->y[77];
  CPG_Dual.d11[1] = ecos_workspace->y[78];
  CPG_Dual.d11[2] = ecos_workspace->y[79];
  CPG_Dual.d11[3] = ecos_workspace->y[80];
  CPG_Dual.d11[4] = ecos_workspace->y[81];
  CPG_Dual.d11[5] = ecos_workspace->y[82];
  CPG_Dual.d11[6] = ecos_workspace->y[83];
  CPG_Dual.d12[0] = ecos_workspace->y[84];
  CPG_Dual.d12[1] = ecos_workspace->y[85];
  CPG_Dual.d12[2] = ecos_workspace->y[86];
  CPG_Dual.d12[3] = ecos_workspace->y[87];
  CPG_Dual.d12[4] = ecos_workspace->y[88];
  CPG_Dual.d12[5] = ecos_workspace->y[89];
  CPG_Dual.d12[6] = ecos_workspace->y[90];
  CPG_Dual.d13[0] = ecos_workspace->y[91];
  CPG_Dual.d13[1] = ecos_workspace->y[92];
  CPG_Dual.d13[2] = ecos_workspace->y[93];
  CPG_Dual.d13[3] = ecos_workspace->y[94];
  CPG_Dual.d13[4] = ecos_workspace->y[95];
  CPG_Dual.d13[5] = ecos_workspace->y[96];
  CPG_Dual.d13[6] = ecos_workspace->y[97];
  CPG_Dual.d14[0] = ecos_workspace->z[224];
  CPG_Dual.d14[1] = ecos_workspace->z[225];
  CPG_Dual.d14[2] = ecos_workspace->z[226];
  CPG_Dual.d14[3] = ecos_workspace->z[227];
  CPG_Dual.d14[4] = ecos_workspace->z[228];
  CPG_Dual.d14[5] = ecos_workspace->z[229];
  CPG_Dual.d14[6] = ecos_workspace->z[230];
  CPG_Dual.d14[7] = ecos_workspace->z[231];
  CPG_Dual.d14[8] = ecos_workspace->z[232];
  CPG_Dual.d14[9] = ecos_workspace->z[233];
  CPG_Dual.d14[10] = ecos_workspace->z[234];
  CPG_Dual.d14[11] = ecos_workspace->z[235];
  CPG_Dual.d14[12] = ecos_workspace->z[236];
  CPG_Dual.d14[13] = ecos_workspace->z[237];
  CPG_Dual.d14[14] = ecos_workspace->z[238];
  CPG_Dual.d15[0] = ecos_workspace->z[239];
  CPG_Dual.d15[1] = ecos_workspace->z[240];
  CPG_Dual.d15[2] = ecos_workspace->z[241];
  CPG_Dual.d15[3] = ecos_workspace->z[242];
  CPG_Dual.d15[4] = ecos_workspace->z[243];
  CPG_Dual.d15[5] = ecos_workspace->z[244];
  CPG_Dual.d15[6] = ecos_workspace->z[245];
  CPG_Dual.d15[7] = ecos_workspace->z[246];
  CPG_Dual.d15[8] = ecos_workspace->z[247];
  CPG_Dual.d15[9] = ecos_workspace->z[248];
  CPG_Dual.d15[10] = ecos_workspace->z[249];
  CPG_Dual.d15[11] = ecos_workspace->z[250];
  CPG_Dual.d15[12] = ecos_workspace->z[251];
  CPG_Dual.d15[13] = ecos_workspace->z[252];
  CPG_Dual.d15[14] = ecos_workspace->z[253];
  CPG_Dual.d16 = ecos_workspace->z[254];
  CPG_Dual.d17[0] = ecos_workspace->y[98];
  CPG_Dual.d17[1] = ecos_workspace->y[99];
  CPG_Dual.d17[2] = ecos_workspace->y[100];
  CPG_Dual.d17[3] = ecos_workspace->y[101];
  CPG_Dual.d17[4] = ecos_workspace->y[102];
  CPG_Dual.d17[5] = ecos_workspace->y[103];
  CPG_Dual.d17[6] = ecos_workspace->y[104];
  CPG_Dual.d17[7] = ecos_workspace->y[105];
  CPG_Dual.d17[8] = ecos_workspace->y[106];
  CPG_Dual.d18[0] = ecos_workspace->y[107];
  CPG_Dual.d18[1] = ecos_workspace->y[108];
  CPG_Dual.d18[2] = ecos_workspace->y[109];
  CPG_Dual.d18[3] = ecos_workspace->y[110];
  CPG_Dual.d18[4] = ecos_workspace->y[111];
  CPG_Dual.d18[5] = ecos_workspace->y[112];
  CPG_Dual.d18[6] = ecos_workspace->y[113];
  CPG_Dual.d18[7] = ecos_workspace->y[114];
  CPG_Dual.d18[8] = ecos_workspace->y[115];
  CPG_Dual.d19 = ecos_workspace->y[116];
  CPG_Dual.d20[0] = ecos_workspace->y[117];
  CPG_Dual.d20[1] = ecos_workspace->y[118];
  CPG_Dual.d20[2] = ecos_workspace->y[119];
  CPG_Dual.d20[3] = ecos_workspace->y[120];
  CPG_Dual.d20[4] = ecos_workspace->y[121];
  CPG_Dual.d20[5] = ecos_workspace->y[122];
  CPG_Dual.d20[6] = ecos_workspace->y[123];
  CPG_Dual.d20[7] = ecos_workspace->y[124];
  CPG_Dual.d20[8] = ecos_workspace->y[125];
  CPG_Dual.d20[9] = ecos_workspace->y[126];
  CPG_Dual.d20[10] = ecos_workspace->y[127];
  CPG_Dual.d20[11] = ecos_workspace->y[128];
  CPG_Dual.d20[12] = ecos_workspace->y[129];
  CPG_Dual.d20[13] = ecos_workspace->y[130];
  CPG_Dual.d20[14] = ecos_workspace->y[131];
  CPG_Dual.d20[15] = ecos_workspace->y[132];
  CPG_Dual.d20[16] = ecos_workspace->y[133];
  CPG_Dual.d20[17] = ecos_workspace->y[134];
  CPG_Dual.d20[18] = ecos_workspace->y[135];
  CPG_Dual.d20[19] = ecos_workspace->y[136];
  CPG_Dual.d20[20] = ecos_workspace->y[137];
  CPG_Dual.d20[21] = ecos_workspace->y[138];
  CPG_Dual.d20[22] = ecos_workspace->y[139];
  CPG_Dual.d20[23] = ecos_workspace->y[140];
  CPG_Dual.d20[24] = ecos_workspace->y[141];
  CPG_Dual.d20[25] = ecos_workspace->y[142];
  CPG_Dual.d20[26] = ecos_workspace->y[143];
  CPG_Dual.d20[27] = ecos_workspace->y[144];
  CPG_Dual.d20[28] = ecos_workspace->y[145];
  CPG_Dual.d20[29] = ecos_workspace->y[146];
  CPG_Dual.d20[30] = ecos_workspace->y[147];
  CPG_Dual.d20[31] = ecos_workspace->y[148];
  CPG_Dual.d20[32] = ecos_workspace->y[149];
  CPG_Dual.d20[33] = ecos_workspace->y[150];
  CPG_Dual.d20[34] = ecos_workspace->y[151];
  CPG_Dual.d20[35] = ecos_workspace->y[152];
  CPG_Dual.d21[0] = ecos_workspace->z[255];
  CPG_Dual.d21[1] = ecos_workspace->z[256];
  CPG_Dual.d21[2] = ecos_workspace->z[257];
  CPG_Dual.d21[3] = ecos_workspace->z[258];
  CPG_Dual.d21[4] = ecos_workspace->z[259];
  CPG_Dual.d21[5] = ecos_workspace->z[260];
  CPG_Dual.d21[6] = ecos_workspace->z[261];
  CPG_Dual.d21[7] = ecos_workspace->z[262];
  CPG_Dual.d21[8] = ecos_workspace->z[263];
  CPG_Dual.d21[9] = ecos_workspace->z[264];
  CPG_Dual.d21[10] = ecos_workspace->z[265];
  CPG_Dual.d21[11] = ecos_workspace->z[266];
  CPG_Dual.d21[12] = ecos_workspace->z[267];
  CPG_Dual.d21[13] = ecos_workspace->z[268];
  CPG_Dual.d21[14] = ecos_workspace->z[269];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (ecos_workspace->info->pcost);
  CPG_Info.iter = ecos_workspace->info->iter;
  CPG_Info.status = ecos_flag;
  CPG_Info.pri_res = ecos_workspace->info->pres;
  CPG_Info.dua_res = ecos_workspace->info->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<438; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<1589; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<153; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<865; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<600; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!ecos_workspace ) {
    cpg_copy_all();
    ecos_workspace = ECOS_setup(438, 600, 153, 270, 46, (int *) &ecos_q, 0, Canon_Params_conditioning.G->x, Canon_Params_conditioning.G->p, Canon_Params_conditioning.G->i, Canon_Params_conditioning.A->x, Canon_Params_conditioning.A->p, Canon_Params_conditioning.A->i, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
  } else {
    if (Canon_Outdated.A || Canon_Outdated.b || Canon_Outdated.G) {
      cpg_copy_all();
      ECOS_updateData(ecos_workspace, Canon_Params_conditioning.G->x, Canon_Params_conditioning.A->x, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
    } else {
      if (Canon_Outdated.h) {
        cpg_copy_h();
        for (i=0; i<600; i++) { ecos_updateDataEntry_h(ecos_workspace, i, Canon_Params_conditioning.h[i]); };
      }
    }
  }
  ecos_workspace->stgs->feastol = Canon_Settings.feastol;
  ecos_workspace->stgs->abstol = Canon_Settings.abstol;
  ecos_workspace->stgs->reltol = Canon_Settings.reltol;
  ecos_workspace->stgs->feastol_inacc = Canon_Settings.feastol_inacc;
  ecos_workspace->stgs->abstol_inacc = Canon_Settings.abstol_inacc;
  ecos_workspace->stgs->reltol_inacc = Canon_Settings.reltol_inacc;
  ecos_workspace->stgs->maxit = Canon_Settings.maxit;
  // Solve with ECOS
  ecos_flag = ECOS_solve(ecos_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
  Canon_Outdated.h = 0;

  ECOS_cleanup(ecos_workspace, 0);
  ecos_workspace = NULL;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.feastol = 1e-8;
  Canon_Settings.abstol = 1e-8;
  Canon_Settings.reltol = 1e-8;
  Canon_Settings.feastol_inacc = 1e-4;
  Canon_Settings.abstol_inacc = 5e-5;
  Canon_Settings.reltol_inacc = 5e-5;
  Canon_Settings.maxit = 100;
}

void cpg_set_solver_feastol(cpg_float feastol_new){
  Canon_Settings.feastol = feastol_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new){
  Canon_Settings.feastol_inacc = feastol_inacc_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_maxit(cpg_int maxit_new){
  Canon_Settings.maxit = maxit_new;
}
